// <auto-generated/>
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using WebApp.Admin.Auth;
using WebApp.Shared.Dtos.Management.Auth;
using JSException = Microsoft.JSInterop.JSException;

namespace WebApp.Admin.Components.Pages.Auth
{
    [AllowAnonymous]
    public partial class Login : IAsyncDisposable
    {
        private AdminLoginDto loginModel = new();
        private bool isSubmitting = false;
        private bool rememberMe = false;
        private bool showPwd { get; set; }
        [SupplyParameterFromQuery]
        public string? error { get; set; }
        private string? errorMessage;
        private List<string>? validationErrors;
        private IJSObjectReference? _jsModule;
        private void TogglePwd() => showPwd = !showPwd;

        // Cấu trúc hứng dữ liệu từ JS
        public class JsLoginResult
        {
            public bool Success { get; set; }
            public string Message { get; set; } = "";
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                try
                {
                    var uri = Navigation.ToAbsoluteUri(Navigation.Uri);
                    if (uri.Query.Contains("ReturnUrl=") || uri.Query.Contains("logout=true"))
                    {
                        await JSRuntime.InvokeVoidAsync("history.replaceState", null, "", "/management/login");
                    }

                    var saveEmail = await JSRuntime.InvokeAsync<string?>("localStorage.getItem", "savedEmail");
                    if (!string.IsNullOrWhiteSpace(saveEmail))
                    {
                        loginModel = loginModel with { UsernameOrEmail = saveEmail };
                        rememberMe = true;
                        StateHasChanged();
                    }
                }
                catch (JSException)
                {
                    // Người dùng có thể bật chặn Cookie trong trình duyệt hoặc chế độ ẩn danh
                }
            }
        }

        protected override async Task OnInitializedAsync()
        {
            if (!string.IsNullOrEmpty(error))
            {
                errorMessage = Uri.UnescapeDataString(error);
            }

            var uri = Navigation.ToAbsoluteUri(Navigation.Uri);
            bool isFromLogout = uri.Query.Contains("logout=true");
            bool isBlockedByMiddleware = uri.Query.Contains("ReturnUrl=");

            // Nếu vừa đăng xuất hoặc bị Middleware chặn truy cập -> Reset state, không Redirect đi đâu cả
            if (isFromLogout || isBlockedByMiddleware)
            {
                if (AuthStateProvider is CustomAuthStateProvider customAuth)
                {
                    customAuth.NotifyUserLogout(); // Gọi hàm reset state (nếu có)
                }
                return;
            }

            var authState = await AuthStateProvider.GetAuthenticationStateAsync();
            if (authState.User.Identity?.IsAuthenticated == true)
            {
                Navigation.NavigateTo("/management/dashboard", replace: true);
            }
        }

        private async Task HandleSubmitAsync()
        {
            isSubmitting = true;
            errorMessage = null;
            validationErrors = null;

            try
            {
                try
                {
                    if (rememberMe)
                    {
                        // Lưu email vào localStorage
                        await JSRuntime.InvokeVoidAsync("localStorage.setItem", "savedEmail", loginModel.UsernameOrEmail);
                    }
                    else
                    {
                        // Xóa email khỏi localStorage
                        await JSRuntime.InvokeVoidAsync("localStorage.removeItem", "savedEmail");
                    }
                }
                catch(JSException) { }

                // 1. Nạp module JS (Đường dẫn tương đối tính từ thư mục wwwroot/app root)
                _jsModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>(
                    "import", "./Components/Pages/Auth/Login.razor.js"); // Điều chỉnh đường dẫn đúng file của bạn

                // 2. Gọi hàm 'submitLoginForm' được export từ module
                var result = await _jsModule.InvokeAsync<JsLoginResult>("submitLoginForm", "nativeLoginForm");

                if (result.Success)
                {
                    Navigation.NavigateTo("/management/dashboard", forceLoad: true);
                }
                else
                {
                    errorMessage = result.Message;
                }
            }
            catch (Exception)
            {
                errorMessage = "Đã xảy ra lỗi trong quá trình đăng nhập. Vui lòng thử lại.";
            }
            finally
            {
                isSubmitting = false;
            }
        }

        // Giải phóng bộ nhớ khi rời khỏi trang Login
        public async ValueTask DisposeAsync()
        {
            try
            {
                if (_jsModule is not null)
                {
                    await _jsModule.DisposeAsync();
                }
            }
            catch (JSDisconnectedException)
            {
                // Xử lý lỗi nếu cần
            }
            
        }
    }
}
