// <auto-generated/>
using Microsoft.JSInterop;
using WebApp.Shared.Dtos.Management.Auth;
using JSException = Microsoft.JSInterop.JSException;

namespace WebApp.Admin.Components.Pages.Auth
{
    public partial class Login
    {
        private AdminLoginDto loginModel = new();
        private bool isSubmitting = false;
        private bool rememberMe = false;
        private string? errorMessage;
        private List<string>? validationErrors;
        
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                try
                {
                    var saveEmail = await JSRuntime.InvokeAsync<string?>("localStorage.getItem", "savedEmail");
                    if (!string.IsNullOrWhiteSpace(saveEmail))
                    {
                        loginModel = loginModel with { UsernameOrEmail = saveEmail };
                        rememberMe = true;
                        StateHasChanged();
                    }
                }
                catch (JSException)
                {
                    // Người dùng có thể bật chặn Cookie trong trình duyệt hoặc chế độ ẩn danh
                }
            }
        }

        private async Task HandleSubmitAsync()
        {
            isSubmitting = true;
            errorMessage = null;
            validationErrors = null;

            try
            {
                try
                {
                    if (rememberMe)
                    {
                        // Lưu email vào localStorage
                        await JSRuntime.InvokeVoidAsync("localStorage.setItem", "savedEmail", loginModel.UsernameOrEmail);
                    }
                    else
                    {
                        // Xóa email khỏi localStorage
                        await JSRuntime.InvokeVoidAsync("localStorage.removeItem", "savedEmail");
                    }
                }
                catch(JSException) { }

                var result = await AuthService.LoginAsync(loginModel);
                if (result.Success && result.Data != null)
                {
                    Navigation.NavigateTo("/management/dashboard", forceLoad: true);
                }
                else
                {
                    errorMessage = result.Message ?? "Tên đăng nhập hoặc mật khẩu không đúng.";
                    validationErrors = result.Errors;
                }
            }
            catch (Exception)
            {
                errorMessage = "Đã xảy ra lỗi trong quá trình đăng nhập. Vui lòng thử lại.";
            }
            finally
            {
                isSubmitting = false;
            }
        }

        private async Task HandleLogout()
        {

        }
    }
}
